name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the use case?
      placeholder: I'm trying to ... but currently ...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: |
        I would like to be able to run:
        ```bash
        skillforge <command> ...
        ```
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any workarounds or alternative approaches you've considered?

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      options:
        - CLI Command
        - Skill Format
        - Testing
        - Versioning
        - MCP Integration
        - Security / Governance
        - Multi-Platform Publishing
        - Analytics
        - Configuration
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: Impact
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would significantly improve my workflow
        - Blocking my use case
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any mockups, examples, or references?
